version: '3'
networks:
  laravel:
services:
  site:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx:/etc/nginx/conf.d
    depends_on:
      - php
      - mysql
    networks:
      - laravel
  php:
    build:
      context: ./
      dockerfile: ./docker/php/php.dockerfile
    volumes:
      - ./:/var/www/html
      - ./docker/php/supervisor:/etc/supervisor/custom.d/
    ports:
      - "9000:9000"
    networks:
      - laravel